### ISSUE TITLE
flashfocus doesn't do anything

### ISSUE THREAD

**Issue by indeedwatson** [fennerm/flashfocus#11]
i thought maybe it was compton, spent some time testing different backends and getting rid of my config entirely, but no matter what flashfocus doesn't do anything visuall

Sample output from running flashfocus on terminal: https://paste.xinu.at/Eydq4/

**Comment by fennerm** [comment]
Could let me know what window manager and distro you're using?

Someone who was having a similar mysterious issue using herbstluftwm reported that using compton's --detect-client-opacity solved it.

**Comment by indeedwatson** [comment]
Arch and i3, sorry. Just tried that flag and didn't change anything. There might be some minor thing that I don't realize that I'm doing wrong.

**Comment by indeedwatson** [comment]
Yes compton is running, I tested several things with it.

I didn't test changing the i3 config as I didn't think it could interfere with this.

For compton, I mostly deleted parts, I can show you my regular config: https://gist.github.com/8c439253dab125e442da331584d1ed4c

**Comment by fennerm** [comment]
Successfully reproduced the problem using your config! I need to figure out the settings necessary in compton to get flashfocus to work so this is really helpful. I'll try to get the bottom of this when I have some time this evening.

**Comment by indeedwatson** [comment]
Oh nice, I wonder why nuking most of the config didn't solve this. Can you give me a compton config that does work so I can confirm?

**Comment by fennerm** [comment]
Here's mine:

```
# Shadow
shadow = false;

# Opacity
inactive-opacity-override = false;
alpha-step = 0.06;
blur-kern = "3x3box";
blur-background-exclude = [
	"window_type = 'dock'",
	"window_type = 'desktop'",
	"_GTK_FRAME_EXTENTS@:c"
];

# Makes flashfocus work with tabbed containers
opacity-rule = [
    "0:_NET_WM_STATE@:32a *= '_NET_WM_STATE_HIDDEN'"
];

# Fading
fading = false;

# Other
backend = "glx";
mark-wmwin-focused = true;
mark-ovredir-focused = true;
use-ewmh-active-win = true;
detect-rounded-corners = true;
detect-client-opacity = true;
refresh-rate = 0;
vsync = "none";
dbe = false;
paint-on-overlay = true;
detect-transient = true;
detect-client-leader = true;
invert-color-include = [ ];
```

**Comment by indeedwatson** [comment]
It works with that, but doing some testing marrying the two configs, I haven't found the exact culprit, but the line `  "95:class_g = 'Termite' && !_NET_WM_STATE@:32a",` which makes termite not draw over itself with transparency when using tabs in i3, makes this not work with termite (all other windows do flash) makes Termite does not flash.

**Comment by fennerm** [comment]
It seems like the key is detect-client-opacity = true. Your config works for me with that line. Let me know if that works on your end.

**Comment by indeedwatson** [comment]
It does but not with termite either, so long as I have that option to not make the transparency stack on itself. At least it's something.

**Comment by fennerm** [comment]
Is your goal to have terminal windows be 95% opacity and all other windows 100%? At the moment this is difficult to get working with flashfocus because it assumes all windows have the same default opacity. I'm planning to add more config options related to this soon though.

**Comment by indeedwatson** [comment]
yeah pretty much. Maybe I'll give up the transparency for a while to switch things up. Thanks for looking into it.

**Comment by fennerm** [comment]
Does `"0:_NET_WM_STATE@:32a *= '_NET_WM_STATE_HIDDEN'"` not prevent the transparency stacking? 

Either way, I'll try to get some more configuration options added soon. Thanks for your time working through this with me :)

**Comment by indeedwatson** [comment]
Actually it seems that it does. Earlier it didn't, not sure what changed.

**Comment by indeedwatson** [comment]
I figured out what was the problem with some windows not flashing, in case you want to know: I have several terminals that open up at startup, such as with vim, and from what I can tell, these are the terminals that have issues with transparency.

**Comment by fennerm** [comment]
Hey fyi, the latest version has options for setting opacity based on window class/id, so your setup should hopefully work now.

**Comment by indeedwatson** [comment]
Thanks for the headsup.

Btw do you happen to know why flashfocus is the only package that gets updated *every* time i run an update on AUR with yay? (I do that like 5 times a day and I doubt you update flashfocus *that* often).

**Comment by fennerm** [comment]
I don't use yay but it could be to do with it being a git package? I've
tried some helpers just redownload git packages every time they update. If
you have other git packages that aren't doing that then I'm not sure :/

**Comment by indeedwatson** [comment]
I do indeed, but it's not a big deal, no worries.
