### ISSUE TITLE
Random high CPU usage

### ISSUE THREAD

**Issue by indeedwatson** [fennerm/flashfocus#13]
Recently I've noticed that flashfocus randomly shoots up my CPU at 90%~ usage.

I don't know the cause, though one possible scenario where this happens might be when I kill my x session and restart it, or when I restart i3 in place. I can't confirm that that's always when it happens, but it's a possibility.

**Comment by fennerm** [comment]
Odd, I definitely haven't seen that on my machine so this may be hard to debug. I might be able to figure something out if you can capture a log while its happening.
