### ISSUE TITLE
Not working with certain windows (emacs?)

### ISSUE THREAD

**Issue by podiki** [fennerm/flashfocus#16]
First of all, thanks for the great project!

I seem to be having an issue in a workspace (using i3-gaps on Arch) if it contains an Emacs window. Then flashfocus will do nothing when switching to/from Emacs and some other windows. Emacs will never flash, nor will e.g Firefox, though with termite will. Here is a sample of the errors I receive when in this workspace:

```
[ 18270.06 ] error    3 BadWindow    request    2 minor    0 serial 3695638: "BadWindow (invalid Window parameter)"
[ 18270.06 ] error    3 BadWindow    request   20 minor    0 serial 3695640: "BadWindow (invalid Window parameter)"
[ 18270.06 ] error    3 BadWindow    request   20 minor    0 serial 3695643: "BadWindow (invalid Window parameter)"
[ 18270.06 ] error    3 BadWindow    request    2 minor    0 serial 3695656: "BadWindow (invalid Window parameter)"
[ 18270.06 ] error    3 BadWindow    request   20 minor    0 serial 3695658: "BadWindow (invalid Window parameter)"
[ 18270.07 ] error    3 BadWindow    request   20 minor    0 serial 3695661: "BadWindow (invalid Window parameter)"
```

Happy to provide anything else that would be useful for debugging.

Edit: The Firefox window that was with Emacs in that workspace also seems to never flash, even when moved to different workspaces (and has same type of errors as above). Not sure what is happening.

**Comment by podiki** [comment]
Update: issue seems to have disappeared after closing the affected windows. I wonder if it was due to something in Firefox (video?), Emacs (no idea), or something I did in i3 in setting this up and trying out window arrangements.

I'll leave this open for now in case we figure something out or if it occurs again.

**Comment by fennerm** [comment]
I've also observed this myself but haven't been able to nail down the cause. I think the proximate issue is a compositor failure, since flashfocus continues to update window properties but no visual change in opacity occurs. Restarting compton also seems to fix the problem.

Debugging compositor errors is a little beyond me tbh, but if anyone has any leads I'd love to hear them.

**Comment by patrick-motard** [comment]
I use emacs and firefox on arch, haven't run into any issues yet.

**Comment by podiki** [comment]
As an update from my end, also have not had this happen again; I will close the issue.
