### ISSUE TITLE
The effect stops working after switching workspaces in i3

### ISSUE THREAD

**Issue by PhilUranus** [fennerm/flashfocus#17]
This is the output. The stack trace is printed as soon as the Firefox window gets focus during the workspace change: [flashfocus.log](https://github.com/fennerm/flashfocus/files/2194608/flashfocus.log)

And the config: [flashfocus.yml.txt](https://github.com/fennerm/flashfocus/files/2194613/flashfocus.yml.txt)

**Comment by fennerm** [comment]
Thanks for the report! This is definitely a bug, I'll get it fixed ASAP

**Comment by fennerm** [comment]
Fixed (f6025d2c7f0f787fd5c1a652d148e70d8b223669) in the latest version, let me know if you have any further problems.
