### ISSUE TITLE
Transparency with flash

### ISSUE THREAD

**Issue by Rackinov** [fennerm/flashfocus#18]
Hi there, loving the flashfocus but I'm struggling to get both transparent windows and the flash to still work.
For example when I run

`flashfocus -e 0.9 -o 0.6`

the flashfocus running terminal flashes correctly when I execute Flash_Window but any new window does not flash at all. (Interestingly when I run compton from a terminal too it flashes correctly but any other terminal window, browser and applications do not flash).
There are no error messages and I believe that compton has all the right bits in the conf. Has anybody managed to get both transparency and the flash to work?

On attached picture compton is running on upper left, flashfocus -e 0.9 -o 0.6 is running on lower left and I have just ran flash_window on the open terminal on the right and it has not flashed.
![flashfocusissue](https://user-images.githubusercontent.com/41784490/43315646-7f2bd5c0-918e-11e8-9770-50d4369ea42e.png)

**Comment by fennerm** [comment]
Thanks for submitting :) Working on a fix.

**Comment by fennerm** [comment]
This should be fixed in the latest version. Let me know if its working for you and I'll close.

**Comment by Rackinov** [comment]
All working great now. Thanks for helping so quickly!
