### ISSUE TITLE
Please keep changelog up to date

### ISSUE THREAD

**Issue by jubalh** [fennerm/flashfocus#19]
Last entry in CHANGELOG.md is for version 1.0.0.
Latest release is 1.0.9. Please keep ChangeLog up to date!

**Comment by fennerm** [comment]
yeah I guess I let that slip. I’ll get that updated over the weekend :)

**Comment by fennerm** [comment]
A week later than promised but changelog is updated, hope you have a good weekend

**Comment by jubalh** [comment]
Cool, thank you!
