### ISSUE TITLE
Stop flashing if only window in workspace

### ISSUE THREAD

**Issue by GandaG** [fennerm/flashfocus#21]
With flash-on-focus and when switching workspaces, the newly focused window is flashed (correctly).
Is it possible to not flash if the new workspace only has 1 window?

**Comment by fennerm** [comment]
I agree that this would be nice, I’ll definitely look into it. I fear that it might be annoyingly difficult to implement due hidden windows, statusbars, window manager differences etc.

**Comment by fennerm** [comment]
This actually seems pretty doable. I'll get this implemented when I find some free time.

**Comment by fennerm** [comment]
flash-lone-windows config option is now implemented on master branch.

```
Possible values:
  'always':
     Always flash lone windows
  'never':
     Never flash lone windows
  'on_open_close':
     Lone windows will be flashed only if a) if they were just opened and b) if 
     another window was just closed. 
  'on_switch':
    Lone windows will be flashed only upon switching desktops.
```

So for your usecase, add the following to your config:
```
flash-lone-windows: 'on_open_close'
```

Or on the CLI:
```
flashfocus --flash-lone-windows on_open_close
```

Closing this issue but feel free to reopen if you encounter problems.

**Comment by GandaG** [comment]
It's perfect now! Thank you very much
