### ISSUE TITLE
[feature request] Ability to specify a config file

### ISSUE THREAD

**Issue by starun96** [fennerm/flashfocus#22]
It would be great if there was a simple "-c [path]" option to specify the config filepath upon executing flashfocus so we don't have to use the default ~/.config filepath.

for example:

```flashfocus -c ~/main/configs/flashfocus.yml```

**Comment by fennerm** [comment]
I agree that this would be useful, I’m pretty tight on time atm so it’ll likely take me a while to look into this. Alternatively I’m more than happy to point you in the right direction if you’re open to implementing this yourself. 

Either way, thanks for the suggestion :)

**Comment by fennerm** [comment]
Finally got a bit of time to implement this. Custom config file location can now be set with the --config/-c flag. Let me know if you have any issues.
