### ISSUE TITLE
Is it possible to not flash if it's the only window in the workspace?

### ISSUE THREAD

**Issue by dhsdshdhk** [fennerm/flashfocus#27]
For example I switch back and forth between workspace 2 with fullscreen firefox and workspace 3 with fullscreen thunar. Is there a rule to prevent flashing in this scenario, or I just rule out both firefox and thunar?

**Comment by fennerm** [comment]
I think the flash-lone-windows option might be what you’re looking for. Documentation is in the config file.

**Comment by dhsdshdhk** [comment]
Thank you. Closed.
