### ISSUE TITLE
Window appears with full opacity before starting to fade in

### ISSUE THREAD

**Issue by KhaimovMR** [fennerm/flashfocus#30]
If `-o` argument has the value of `0` the window that you've switched to is appearing at first in full opacity and only then it's opacity starts to ascend by the calculated amounts.
You could easily reproduce this strange behaviour to run the flashfocus with these parameters:
```
flashfocus -t 20000 -o 0
```
The  problem is in the `set_opacity` function, located in the `flashfocus.xutil` module.

PS: I've done the fix and it's coming in PR.

**Comment by fennerm** [comment]
Fixed in v 2.0.0
