### ISSUE TITLE
Flashfocus seems to override other window opacities

### ISSUE THREAD

**Issue by BlueDrink9** [fennerm/flashfocus#35]
In my compton.conf:
```
inactive-window-opacity = 1;
inactive-opacity = 0.95;
{a custom window rule}
```

Without flashfocus running, compton displays these correctly. When I start FF, these become fully opaque.

I understand that the current max opacity is configurable. Could this instead be set to whatever compton would use for it?

Lmk if you need me to provide any more info.

**Comment by fennerm** [comment]
Yes flashfocus will override opacity settings set in your compton config. You can set the default opacity of all windows to 0.95 but currently there is no way to set different default opacity for focused vs non-focused windows.

**Comment by BlueDrink9** [comment]
That's a shame. Is it something you've looked into adding?

**Comment by fennerm** [comment]
Just to make sure I’m understanding, could you describe for me the effect you’re trying to achieve?

**Comment by BlueDrink9** [comment]
Say I have inactive windows set at 0.5 opacity in compton, and active windows at 0.9. When I switch to a window, I would like it to flash from 0.1 to [active window value from compton], and for the old window to become 0.5.

Currently, I can set the active window to flash from 0.1 to 0.9 in flashfocus, but not inactive windows. They are set at 1 when I use ff.

**Comment by fennerm** [comment]
This isn't something I'm super interested in implementing at the moment. I don't really think flashfocus is necessary if you're dimming inactive windows (and vice versa). It would also add a decent amount of code complexity.

I'll keep it in mind though and it may be something I'll reconsider later.
