### ISSUE TITLE
Needs to be killed manually if exiting the WM

### ISSUE THREAD

**Issue by ReekyMarko** [fennerm/flashfocus#40]
If I exit my WM, and even relogin and then start the WM back up again, flashfocus is not working anymore. I need to run `killall flashfocus` and then start the WM again (or run flashfocus manually) to get it working again.

I'm on arch linux + swaywm with the latest flashfocus-git from the AUR

**Comment by Artturin** [comment]
a workaround is to add `exec pkill autotiling` in your config before flashfocus

**Comment by fennerm** [comment]
@ReekyMarko I think setting flashfocus up as a systemd service should solve this - https://github.com/fennerm/flashfocus/wiki#systemd-config. Closing this out.
