### ISSUE TITLE
Where and how can I change the flash function ?

### ISSUE THREAD

**Issue by sucrecacao** [fennerm/flashfocus#41]
Hello,
Instead of making a transparent background fading transition, I would like to have a fading border transition and/or fading white "flash".

And hint and pointers on how I could implements that ? 

Thanks !

**Comment by sucrecacao** [comment]
I haven't found any function in `xpybutil` library that allow you to add border or a color filter on a window. 
So I guess its beyond my expertise too.

But big kuddos for the source code, so neat and so clean. I was very easy to read and understand, a real pleasure !

**Comment by fennerm** [comment]
Thanks :). Closing this, feel free to reopen if you change your mind.
