### ISSUE TITLE
Flashfocus doesn't recognise Rofi window

### ISSUE THREAD

**Issue by develFoss** [fennerm/flashfocus#49]
Flashfocus doesn't seem to recognize rofi window, even if I put rule for Rofi class in config file.
"INFO: Window .... is not visible, ignoring..."
Note that I have no opacity rule for rofi in compton.

OS: Arch Linux x86_64
WM: i3-gaps
All package compton-tryone-git, rofi, flashfocus-git from aur and main repository.

**Comment by fennerm** [comment]
Probably rofi has some unconventional window properties. I’m a little split on whether it would even be such a good thing for flashfocus to affect rofi given that its usually pretty clear when rofi has focus.

I’d accept a PR to get this working as a config option but probably won’t implement this myself. Thanks for taking the time to file the bug report though!

**Comment by develFoss** [comment]
I tested it for a bit and it seems to not recognize Polybar and Dunst too, but I agree those are useless (and bad) to flash anyways. So yeah, it might be caused due to some window's properties. I've not gone through all your code to understand what exactly does this, so sadly I can't make a more thorough report.

Thanks for the reply. I really love this nice project. Hope you keep maintaining it.
