### ISSUE TITLE
Install using anaconda

### ISSUE THREAD

**Issue by minhduc0711** [fennerm/flashfocus#50]
I'm wondering if it's possible to install flashfocus using conda? If yes, how would I change my i3 configs?

p/s: I'm new to WMs, sorry for the noob questions and thanks in advance

**Comment by fennerm** [comment]
There is no conda package available for flashfocus. You could try installing pip in your conda env and then installing with pip:
```
conda install pip
pip install flashfocus
```
No changes would be necessary to your config except for the ones mentioned in the READMe.

Have never tried it myself so ymmv.

**Comment by minhduc0711** [comment]
Turns out I forgot to activate the conda env before running flashfocus in i3 configs. Thank you anyways!
