### ISSUE TITLE
[Request] Change flash color

### ISSUE THREAD

**Issue by Cyberdr3am** [fennerm/flashfocus#53]
Hi,

Thx for your work i love it.
Can you add the possibility to change the color during the flash.

So it will be possible with the configuration file to choose through a color code the color of the flash that you want.

Thx

**Comment by fennerm** [comment]
@Cyberdr3am Closing this as a duplicate of https://github.com/fennerm/flashfocus/issues/1. Very much on board with this suggestion but it would require some major changes to the way flashfocus works
