### ISSUE TITLE
cli '-l' short parameter overloaded with log level and flash lone windows

### ISSUE THREAD

**Issue by marty-oehme** [fennerm/flashfocus#54]
On the current master branch, cli.py defines the short option for both flashing lone windows and for setting the log level output to `-l` ([here](https://github.com/fennerm/flashfocus/blob/master/flashfocus/cli.py#L87%23L95)).

That means currently, loglevel overrides lone windows setting -- when doing e.g. `flashfocus -l never` it will complain that never is not a valid option for loglevels.

Perhaps reverting the loglevel short parameter to its previous 'verbosity' `-v` might be an option?

Thank you for the awesome software fennerm!

**Comment by fennerm** [comment]
Oof not my best moment. That seems like a reasonably solution to me, will put a patch together this afternoon.

**Comment by fennerm** [comment]
Alright should be fixed in v2.2.1 @marty-oehme. Thanks for reporting!
