### ISSUE TITLE
Effect not applied to fullscreen window

### ISSUE THREAD

**Issue by Isti115** [fennerm/flashfocus#55]
Probably the most often occurring cause of losing track of the active window for me is when I have something on full screen, thus it does not have a border to help distinguish it, so I was hoping that this nice little program could help me solve this, but as far as my experiences show, in sway (1.5) invoking `flash_window` has no effect on full screen programs. (I bound it to a key, which works otherwise.)

---

Edit: I've just noticed that there is an option in the config file for `flash-fullscreen`, but the default value is true and still, nothing happens.

**Comment by fennerm** [comment]
Hi @Isti115, yep seems like a bug, thanks for reporting. Looking into it.

**Comment by fennerm** [comment]
Unfortunately this looks to be due to a sway design decision @Isti115 - https://github.com/swaywm/sway/issues/3624#issuecomment-461910064. I don't think this behavior is fixable without radically changing how flashfocus works. 

I'll update flashfocus to emit a warning in this scenario.
