### ISSUE TITLE
flashfocus is removing transparency

### ISSUE THREAD

**Issue by adelin-b** [fennerm/flashfocus#58]
Hello,
I just noticed that when flashfocus is triggered it remove the original transparency set through a previous xprop. (using devilspie or glassit in vscode for example)
So I think instead of blinking and going full opacity it should save the current xprop setting and restore them 

![bug flashfocus xprop2](https://user-images.githubusercontent.com/23508913/90979806-c946d780-e557-11ea-85a7-90fa7943297a.gif)

**Comment by fennerm** [comment]
I have considered this implementation but it adds a lot of incidental complexity. I'm wondering, can you achieve the behavior you're looking for by setting flash rules in your config for vscode etc?

**Comment by adelin-b** [comment]
I do not understand what you call a flash rule in my config exactly, vscode or xprops previously setted properties cannot be aware that they are getting flashed by flash focus.

**Comment by adelin-b** [comment]
I think the param `default_opacity` isn't correctly set to the actual default opacity of the window

**Comment by fennerm** [comment]
@adelin-b There are instructions for setting up flash rules in  https://github.com/fennerm/flashfocus/wiki#defining-window-specific-flash-rules-in-config-filei (and also the config file itself).

**Comment by fennerm** [comment]
Hey @adelin-b closing this issue but feel free to reopen if you can't get the flash rules working how you want them.
