### ISSUE TITLE
ModuleNotFoundError: No module named 'six'

### ISSUE THREAD

**Issue by icf20** [fennerm/flashfocus#6]
```
flashfocus
Traceback (most recent call last):
  File "/usr/bin/flashfocus", line 7, in <module>
    from flashfocus.cli import cli
  File "/usr/lib/python3.6/site-packages/flashfocus/cli.py", line 9, in <module>
    from flashfocus.flasher import Flasher
  File "/usr/lib/python3.6/site-packages/flashfocus/flasher.py", line 10, in <module>
    from xcffib.xproto import WindowError
  File "/usr/lib/python3.6/site-packages/xcffib/__init__.py", line 20, in <module>
    import six
ModuleNotFoundError: No module named 'six'

```
`pip install six` solves this but imo need to be placed on readme

**Comment by bbenne10** [comment]
If you install this package with `pip` this is taken care of for you. How did you get flashfocus installed? The readme documents `pip install flashfocus` to install from pypi. (I haven't tried, but I would also imagine you could clone, cd into the cloned directory, and then `pip install .` or `pip install -e .`)

These are all pretty standard ways of getting a python tool working, and I'm not sure that any more docunentation is really necessary (especially if someone is avoiding installing from pypi), but I've got no real say in the project.

**Comment by fennerm** [comment]
I appreciate you opening the issue but I'm with @bbenne10 that this doesn't warrant any further action. xcffib also seems to declare the dependency appropriately.

**Comment by icf20** [comment]
i did install using `pip install flashfocus`

**Comment by fennerm** [comment]
Maybe related to https://github.com/pypa/setuptools/issues/1042 (bug in setuptools v36)? Regardless this is unlikely to be an issue with flashfocus since it doesn't directly require six. Luckily this seems to be easily fixed by reinstalling six so closing for now. Thanks again!

**Comment by bbenne10** [comment]
Interesting. I had assumed you'd have installed using a git clone without using pip. 

I'm running void at home as well. Once I get home I'll try to install and see how it goes. Considering voidlinux's more "cutting edge" rolling release idea, I doubt you've got setuptools <= 36 any longer. 

If I can dig up more information that points here (or even is interesting), I'll post it here.
