### ISSUE TITLE
How to use nc_flash_window instead of flash_window

### ISSUE THREAD

**Issue by plasmoduck** [fennerm/flashfocus#62]
I can flash the window running the 'nc_flash_window' command, but how do I make flashfocus use nc_flash_window all the time instead of flash_window? I have netcat installed on FreeBSD.

**Comment by plasmoduck** [comment]
  ~ nc_flash_window
nc: invalid option -- q
usage: nc [-46DdEFhklNnrStUuvz] [-e policy] [-I length] [-i interval] [-O length]
          [-P proxy_username] [-p source_port] [-s source] [-T ToS]
          [-V rtable] [-w timeout] [-X proxy_protocol]
          [-x proxy_address[:port]] [destination] [port]

**Comment by plasmoduck** [comment]
I can flash the window running the 'nc_flash_window' command, but how do I make flashfocus use nc_flash_window all the time instead of flash_window?

**Comment by fennerm** [comment]
Hi @plasmoduck you should just be able to call the script in bin/nc_flash_window. lmk if you run into issues

**Comment by fennerm** [comment]
Hi @plasmoduck openbsd netcat is only necessary for flashing the window on command. It wouldn't improve performance for flashing windows on focus shift.

**Comment by plasmoduck** [comment]
Fair enough... Thanks.
