### ISSUE TITLE
Window appears with full opacity before starting to fade in (Wayland)

### ISSUE THREAD

**Issue by and3rson** [fennerm/flashfocus#67]
When switching between tabs or workspaces, the target window appears fully opaque for a moment before starting to fade.

System: Arch Linux, Sway 1.6.1, Wayland 1.19.0

Might be related to #30.

**Comment by fennerm** [comment]
I wasn't able to reproduce this with the default flashfocus config.

**Comment by fennerm** [comment]
Closing this out due to inactivity, please re-open with more details if this is still an issue :pray:
