### ISSUE TITLE
Window after focus not returning to unfocused value

### ISSUE THREAD

**Issue by Wiener234** [fennerm/flashfocus#70]
My problem is that when I focus my terminal window and unfocus it the value for focused is set. So i have my terminal with a opacity of 90 set and focus another window the opacity doesn't change to 70 how it is set in picom. My terminal opacity is set in the kitty config to 90.

https://user-images.githubusercontent.com/70913337/159959743-b27db30a-92f8-4b10-bb93-962506a4a84b.mp4

.

**Comment by mateusPreste** [comment]
i have this exactly same issue

**Comment by fennerm** [comment]
@Wiener234 @mateusPreste Do you have "default-opacity" set in your flashfocus config? You'll want it to match your default window opacity. If you have different default opacity configured per-application you can set that up using [rules](https://github.com/fennerm/flashfocus/wiki#defining-window-specific-flash-rules-in-config-file).

**Comment by fennerm** [comment]
Closing this out due to inactivity, please re-open with more details if this is still an issue :pray:
